########################################
## CONFIG | Kafka Configs
########################################
aissemble-kafka-chart:
  kafka:
    commonAnnotations:
        example-annotation: "$getConfigValue(groupName=values;propertyName=name)"
    commonLabels:
      aissemble-configuration-store: "enabled"
      newlabel: "anewlabel"
    resources:
      limits:
        memory: 2G
    autoCreateTopicsEnable: true # Enable auto creation of topics
