########################################
## CONFIG | Configuration Store Configs
## See aiSSEMBLE aissemble-configuration-store-chart: README for more details.
## https://github.com/boozallen/aissemble/
########################################

aissemble-configuration-store-chart:
  aissemble-quarkus-chart:
    app:
      name: "configuration-store"
    deployment:
      env:
        - name: BASE_PROPERTY
          value: /configurations/base
        - name: ENVIRONMENT_PROPERTY
          value: /configurations/env
      supplementalVolumes:
        - name: configurations
          persistentVolumeClaim:
            claimName: configuration-store-claim
      supplementalVolumeMounts:
        - name: configurations
          mountPath: "/configurations"

  # Update 'volumePathOnNode' with the absolute path of the config files to be loaded into the configuration store. 
  # Example '/Users/MyUser/my-project/resources/configs'
  #
  # For WSL users, the configuration files need to be in an accessible path.
  # Example: '/mnt/c' or '/mnt/wsl/rancher-desktop'
  configurationVolume:
    storageType: "local"
    volumePathOnNode: "/Users/ewilkins/dev/aiops/init-tests/oneoff/dev-488/configs"
